### PR TITLE
Formats G Suite Spec to Markdown

### PR DESCRIPTION
**Pull request by grant**
Part of #1.

### CODE REVIEW

**Comment by grant** [comment]
Can you look at this PR? I spent a bit of time working on it a month ago.

**Comment by grant** [comment]
@sveinugu Can you let me know when you have the time to look at this?

**Comment by sveinugu** [comment]
@grant Sorry, but I have two weeks left of my vacation and will have time to look at it after that. Thanks for the help!

**Comment by grant** [comment]
Hey @sveinugu, do you want me to close this PR? Can we merge?
I'm trying to fix the issue you filed on March 5th.

**Comment by grant** [comment]
Hi @sveinugu, Can you please look at this?

**Comment by grant** [comment]
@sveinugu Are you off vacation and able to merge this open source contribution?

**Comment by sveinugu** [comment]
@grant Hehe, I did finish my summer vacation half a year ago..

Sorry for not responding on this. 

First, thanks for the pull request. I did look at it some time this autumn. First off, you did a great initial job getting the specification over to Markdown. However, the effort did not fully have the level of detail and clarity that I wanted for a technical specification of this type. So I started working my way through your initial file, improving it here and there. However, something more important came up, so I stopped half-way, and have not had time to come back to it since.

I should of course have informed you about the status, so sorry about that.

I think I will be able to finish it up soon. Your work was in any case very useful to me, so thanks!

**Comment by grant** [comment]
No worries. :)
I am here to help contribute. Let me know if I can do anything to help.

**Comment by grant** [comment]
If we want to review and merge this PR, let's please do so.

Here is the rendered MD:
https://github.com/gtrack/gtrack/blob/8cf15fa53d81fa049041bf60cf9febd2910e36a6/gsuite/spec/GSuite_specification.md

If there are specific comments, please reply to this PR so I can fix them.
If there is a worry that I forgot something in the conversion, we have the option of keeping both copies and eventually deleting one.

I'm going to close this PR if there are no addressable comments after 12 months.

I'm really doing this as a contribution, but I can't leave PRs open for so long. This project seems abandoned.

I'm not sure what is being worked on with the [gsuite org](https://github.com/gsuite), but eventually, I'd like to submit this PR, create the logos, and actively add open source content there.

**Comment by grant** [comment]
@sveinugu Can you take a look at this?

**Comment by grant** [comment]
I sent another email today about this.

**Comment by grant** [comment]
Hey @sveinugu,
I've spent a number of hours on this, but it seems like this PR can't make progress and the `gsuite` org is not being publicly used.
I can't do anything to contact Sveinung and Eivind. I've checked the UiO website, and it seems like we're in the Autumn 2019 academic season.

I'm really not sure what to do, trying to create a win-win situation, but can't make progress.
As a result, I'll close this PR and stop this effort.

**Pull request closed without merging**
